spring:
  datasource:
    url: jdbc:postgresql://192.168.10.32:5432/nexttutordb
    username: nxtutor
    password: NxTut0r2025
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.cuongpt.nexttutor: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
